scrape_configs:
  - job_name: 'spring-boot-prometheus-grafana-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: ['192.168.1.3:8081']
      - targets: [ 'spring-boot-prometheus-grafana:8081' ]